[package]
name = "fate_rt"
version.workspace = true
edition = "2021"

[dependencies]
fate_graphic = { path = "../fate_graphic", version = "0.1.0" }
anyhow = "1"
cgmath = "0.18"
image = "0.24.8"
rand = "*"
rayon = "1.8.1"
